<?php
  $lang['number']		= 'RÉfÉrence';
  $lang['date']			= 'Date de facturation';
  $lang['due']			= 'Date d\'échéance';
  $lang['to']			= '';
  $lang['from']			= '';
  $lang['product']		= 'Produit';
  $lang['qty']			= 'Montant';
  $lang['price']		= 'Prix';
  $lang['discount']		= 'RÉduction';
  $lang['vat']			= 'TVA';
  $lang['total']		= 'Total';
  $lang['page']			= 'Page';
  $lang['page_of']		= 'de';
?>