<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/account-list">Comptes</a></li>
                        <li class="breadcrumb-item active">Nouveau compte</li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Ajout d'un nouveau compte</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Nom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" id="firstname" name="firstname" value="" parceholder="Entrez le nom" class="form-control">
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Prénom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" id="lastname" name="lastname" value="" parceholder="Entrez le prenom" class="form-control">
                                                </div>
                                            </div>
                                            
                                
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Email
                                                </label>
                                                <div class="col-sm-7">
                                                    <input type="email" id="email" name="email" value="" parceholder="Entrez l'adresse email" class="form-control">
                                                </div>
                                            </div>
                                            
                                         
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Identifiant</label>
                                                <div class="col-sm-5">
                                                    <input type="text" id="login" name="login" value="" parceholder="Entrez l'identifiant" class="form-control">
                                                </div>
                                            </div>
                                       
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Mot de passe</label>
                                                <div class="col-sm-5">
                                                    <input type="password" id="pass" name="pass" value="" parceholder="Entrez le mot de passe" class="form-control">
                                                </div>
                                            </div>
                                            
                               
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Confirmation</label>
                                                <div class="col-sm-5">
                                                    <input type="password" id="confirm" name="confirm" value="" parceholder="Entrez la confirmation" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <br />
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/account-list" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Ajouter</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>
            
            
 <script>
  
  
  $(".form-horizontal").validate({

    rules: {

        firstname: {
               required: true,
            },
        lastname: {
               required: true,
            },
            
        email: {
                email:true, 
            },
            
        login: {
                 required:true, 
                 minlength:5,
            },
            
        pass: {
                 required:true, 
                 minlength:5,
                 equalTo: "#confirm",
            },
            
        confirm: {
                 required:true, 
                 minlength:5,
                 equalTo: "#pass",
            },
            

        
      },
    
    messages: {
        firstname: "Entrer le nom",
        lastname: "Entrer le  pr&eacute;nom",
        email: "Entrer une adresse mail valide",
        login:{
                 required  : "Entrer le login",
                 minlength : "Minimum 5 caractères",
        },
        
        pass:{
                  required  : "Entrer le mot de passe",
                  minlength : "Minimum 5 caractères",
                  equalTo   : "Le mot de passe et la confirmation doivent être identiques",
        },
        
        confirm:{
                  required  : "Entrer la confirmation de mot de passe",
                  minlength : "Minimum 5 caractères",
                  equalTo   : "Le mot de passe et la confirmation doivent être identiques",
        },
    },
    
    
    submitHandler: function(form, event)
    { 
       event.preventDefault();
        form.submit();

    },
 
    

    errorElement : 'div',
    errorPlacement: function(error, element) {
      var placement = $(element).data('error');
      if (placement) {
        $(placement).append(error)
      } else {
        error.insertAfter(element);
      }
    }
 });
  
  </script>            
