<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
                        <li class="breadcrumb-item"><a href="/employee">Employés</a></li>
                        <li class="breadcrumb-item active">Nouvel employé</li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <a href="#" id="employeeSupprimer" class="dropdown-item"> <i class="fa fa-times"></i>Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Ajouter un employé</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Nom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" name="firstname" value="" parceholder="Entrez le nom du employee" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Prénom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" name="lastname" value="" parceholder="Entrez le prenom du employee" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                    <label class="col-sm-3 form-control-label">Actif</label>
                                                <div class="col-sm-9">
                                                    <div>
                                                        <input id="isActive" type="radio" checked="" value="1" name="isActive">
                                                        <label for="optionsRadios1">Activé</label>
                                                    </div>
                                                    <div>
                                                        <input id="isActive" type="radio" value="0" name="isActive">
                                                        <label for="optionsRadios2">Désactivé</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/employee" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>
            
            
<script>
$(".form-horizontal").validate({

    rules: {

        firstname: {
               required: true,
               minlength:2,
            },
        lastname: {
               required: true,
               minlength:2,
            },
            
        
        
      },
    
    messages: {
        firstname: {
                      required: "Entrer le nom",
                      minlength:"Minimum 2 caractères",  
        },
        lastname:{
                      required: "Entrer le  pr&eacute;nom",
                      minlength:"Minimum 2 caractères",
        },
    },
    
    
    submitHandler: function(form, event)
    { 
       event.preventDefault();
        form.submit();

    },
 
    

    errorElement : 'div',
    errorPlacement: function(error, element) {
      var placement = $(element).data('error');
      if (placement) {
        $(placement).append(error)
      } else {
        error.insertAfter(element);
      }
    }
 });
  
  </script>            
