<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/payment">Moyens de paiment</a></li>
                        <li class="breadcrumb-item active">Nouveau moyen de paiement</li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Ajouter un moyen de paiement</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                            
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Moyen de paiement</label>
                                                <div class="col-sm-5">
                                                    <input type="text" name="PaymentLabel" value="" parceholder="Entrez le moyen de paiement" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                         
                                       
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/payment" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>