<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/product">Produit</a></li>
                        <li class="breadcrumb-item active">Nouveau Produit</li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Aujouter un produit</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label">Nom</label>
                                                <div class="col-sm-9">
                                                    <input type="text" name="label" value="" parceholder="Entrez le nom du product" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label">Prix en € TTC<br><small class="text-primary">Ex:  25.80</small></label>
                                                <div class="col-sm-9">
                                                    <input type="text" name="preTaxPrice" parceholder="Entrez le prix du product" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label">Tva en % <br><small class="text-primary">Ex:  25</small></label>
                                                <div class="col-sm-9">
                                                    <input type="text" name="VAT" value="" parceholder="Entrez la tva du product" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label">Catégorie</label>
                                                <div class="col-sm-9 select">
                                                    <select name="idcategories" class="form-control">
                                                        <?php foreach( $categories as $categorieKey => $categorieVal): ?>
                                                            <option <?php echo ($val == $categorieVal["label"])?"selected":"" ?> value="<?= $categorieVal["idcategories"] ?>"><?= $categorieVal["label"] ?></option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                    <label class="col-sm-3 form-control-label">Actif</label>
                                                <div class="col-sm-9">
                                                    <div>
                                                        <input id="isActive" type="radio" checked="" value="1" name="isActive">
                                                        <label for="optionsRadios1">Activé</label>
                                                    </div>
                                                    <div>
                                                        <input id="isActive" type="radio" value="0" name="isActive">
                                                        <label for="optionsRadios2">Désactivé</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/product" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Ajouter</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>