<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/client">Clients</a></li>
                        <li class="breadcrumb-item active">
                            <?= $client['firstname'].' '.$client['lastname'] ?>
                        </li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <a data-toggle="modal" data-target="#myModal" id="clientSupprimer" class="dropdown-item"> <i class="fa fa-times"></i>Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" class="modal fade text-left" style="display: none;" aria-hidden="true">
                                        <div role="document" class="modal-dialog" style=" margin-top: 10%; ">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h4 id="exampleModalLabel" class="modal-title">Suppression</h4>
                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                            <p>Êtes-vous sûr de vouloir supprimer ce client ?</p>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Non</button>
                                            <a href="/client-delete/<?= $client["idClients"] ?>" style="color:#fff"><button type="button" class="btn btn-primary">Oui</button></a>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Modification d'un client</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <?php  foreach( $client as $key => $val):  ?>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label">
                                                <?php 
                                                if($key == "idClients") echo"Id client"; 
                                                elseif($key == "firstname") echo"Nom"; 
                                                elseif($key == "lastname") echo"Prénom"; 
                                                elseif($key == "phonenumber") echo"Téléphone"; 
                                                elseif($key == "postcode") echo"Code postal"; 
                                                elseif($key == "email") echo"Email"; 
                                                elseif($key == "age") echo"Age"; 
                                                elseif($key == "created") echo"Date de création";
                                                ?>
                                                </label>
                                                <div class="col-sm-9">
                                                    <input type="<?php echo (isset($type[$key]))?$type[$key]: 'text'; ?>" name="<?= $key ?>" <?php if($key == "idClients" || $key == "created"){echo 'disabled=""';} ?> value="<?= $val ?>" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <?php endforeach; ?>
                                            <?php foreach( $champs as $champ): ?>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label"><?= $champ["libelle"] ?></label>
                                                <div class="col-sm-9">
                                                    <input type="text" data-id="<?= $champ["idchamps"] ?>" name="<?= $champ["libelle"] ?>" value="<?= $champ["valeur"] ?>" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <?php endforeach; ?>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/client" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Modifier</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>
            
 <script>
  
  
  $(".form-horizontal").validate({

    rules: {

        firstname: {
                    required: true,
                    minlength:2,
            },
        lastname: {
               required: true,
                minlength:2,
            },
        postcode:{
                    minlength:5, 
        },
            
        email: {
                email:true, 
            },
        
        phonenumber:{
            minlength:10,
        }
            
        
      },
    
    messages: {
        firstname:{
                      required: "Entrer le nom",
                      minlength:"Minimum 2 caractères",
        }, 
        lastname: {
                      required: "Entrer le  pr&eacute;nom",
                      minlength:"Minimum 2 caractères",
        },
        
        postcode : "Minimum 5 caractères",
        email: "Entrer une adresse mail valide",
        phonenumber: "Minimum 10 caractères",
    },
    
    
    submitHandler: function(form, event)
    { 
       event.preventDefault();
        form.submit();

    },
 
    

    errorElement : 'div',
    errorPlacement: function(error, element) {
      var placement = $(element).data('error');
      if (placement) {
        $(placement).append(error)
      } else {
        error.insertAfter(element);
      }
    }
 });
  
  </script> 