<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/product">Produit</a></li>
                        <li class="breadcrumb-item active">
                            <?= $product['label']?>
                        </li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <a data-toggle="modal" data-target="#myModal" id="clientSupprimer" class="dropdown-item"> <i class="fa fa-times"></i>Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" class="modal fade text-left" style="display: none;" aria-hidden="true">
                                        <div role="document" class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h4 id="exampleModalLabel" class="modal-title">Suppression</h4>
                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                            <p>Êtes-vous sûr de vouloir supprimer ce produit ?</p>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Non</button>
                                            <a href="/product-delete/<?= $product['Id'] ?>" style="color:#fff"><button type="button" class="btn btn-primary">Oui</button></a>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Modification d'un produit</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <?php foreach( $product as $key => $val): ?>
                                            <div class="form-group row">
                                                <label class="col-sm-3 form-control-label"><?php 
                                                                                           if($key == 'Id') echo 'Id';
                                                                                           if($key == 'Prix') echo 'Prix';
                                                                                           if($key == 'label') echo 'Nom';
                                                                                           if($key == 'categorie') echo 'Catégorie'; 
                                                                                           if($key == 'Tax') echo 'TVA';
                                                                                           if($key == 'isActive') echo 'Actif';
                                                                                           if($key == 'created') echo 'Créé le';
                                                                                           
                                                                                           ?>
                                                                                           </label>
                                                <?php if($key == "isActive"): ?>
                                                <div class="col-sm-9">
                                                    <div>
                                                        <input id="isActive" type="radio" <?php if($val == 1){echo 'checked=""';} ?> value="1" name="isActive">
                                                        <label for="optionsRadios1">Activé</label>
                                                    </div>
                                                    <div>
                                                        <input id="isActive" type="radio" <?php if($val != 1){echo 'checked=""';} ?> value="0" name="isActive">
                                                        <label for="optionsRadios2">Désactivé</label>
                                                    </div>
                                                </div>
                                                <?php elseif($key == "categorie"): ?>
                                                    <div class="col-sm-9 select">
                                                        <select name="idcategories" class="form-control">
                                                            <?php foreach( $categories as $categorieKey => $categorieVal): ?>
                                                                <option <?php echo ($val == $categorieVal["label"])?"selected":"" ?> value="<?= $categorieVal["idcategories"] ?>"><?= $categorieVal["label"] ?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </div>
                                                <?php else: ?>
                                                <div class="col-sm-9">
                                                    <input type="<?php echo (isset($type[$key]))?$type[$key]: 'text'; ?>" name="<?= $key ?>" <?php if($key == "Id" || $key == "created"){echo 'disabled=""';} ?> value="<?= $val ?>" class="form-control">
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                            <div class="line"></div>
                                            <?php endforeach; ?>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/product" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Modifier</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>