<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="/payment">Moyens de paiement</a></li>
                        <li class="breadcrumb-item active">
                            <?= $payment['PaymentLabel'] ?>
                        </li>
                    </div>
                </ul>
                <!-- Forms Section-->
                <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                                    
                                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" class="modal fade text-left" style="display: none;" aria-hidden="true">
                                        <div role="document" class="modal-dialog" style=" margin-top: 10%; ">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h4 id="exampleModalLabel" class="modal-title">Suppression</h4>
                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                            <p>Êtes-vous sûr de vouloir supprimer ce moyen de paiement ?</p>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Non</button>
                                            <button type="button" class="btn btn-primary">Oui</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Modification d'un moyen de paiement</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                        <div  class="form-group row"></div>
                                            <?php foreach( $payment as $key => $val):
                                                if($key == "PaymentLabel")   $key = "Moyen de paiement";
                                            
                                            
                                            if($key =="Moyen de paiement"){ 
                                            ?>
                                            
                                            
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label"><?=$key; ?></label>
                                                <?php
                                                    if($key == "Moyen de paiement")
                                                        $key = "PaymentLabel";
                                                    ?>
                                              
                                                <div class="col-sm-5">
                                                    <input type="<?php echo (isset($type[$key]))?$type[$key]: 'text'; ?>" name="<?= $key ?>"  value="<?= utf8_decode($val) ?>" class="form-control">
                                                </div>
                                               
                                              
                                            </div>
                                            <?php }?>
                                           
                                            <?php endforeach; ?>
                                             <div class="line"></div>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/payment" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Modifier</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>