<?php require __DIR__."/menu.phtml" ?>
<!-- Dashboard Counts Section -->
<section class="dashboard-counts no-padding-bottom">
    <div class="container-fluid">
        <div class="row bg-white has-shadow">
            <!-- Item -->
            <?php if(isset($nbClient) || $nbClient != NULL): ?>
            <div class="col-xl-4 col-sm-6">
                <div class="item d-flex align-items-center">
                    <div class="icon bg-violet"><i class="icon-user"></i></div>
                    <div class="title"><span>Clients</span>
                        <div class="progress">
                            <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-violet"></div>
                        </div>
                    </div>
                    <div class="number"><strong><?= $nbClient ?></strong></div>
                </div>
            </div>
            <?php endif; ?>
            <!-- Item -->
            <?php if(isset($nbTransactionCancel) || $nbTransactionCancel != NULL): ?>
            <div class="col-xl-4 col-sm-6">
                <div class="item d-flex align-items-center">
                    <div class="icon bg-red"><i class="icon-padnote"></i></div>
                    <div class="title"><span>Transactions<br>annulées</span>
                        <div class="progress">
                            <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-red"></div>
                        </div>
                    </div>
                    <div class="number"><strong><?= $nbTransactionCancel ?></strong></div>
                </div>
            </div>
            <?php endif; ?>
            <!-- Item -->
            <?php if(isset($nbTransactionFinish) || $nbTransactionFinish != NULL): ?>
            <div class="col-xl-4 col-sm-6">
                <div class="item d-flex align-items-center">
                    <div class="icon bg-green"><i class="icon-bill"></i></div>
                    <div class="title"><span>Transactions<br>terminées</span>
                        <div class="progress">
                            <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-green"></div>
                        </div>
                    </div>
                    <div class="number"><strong><?= $nbTransactionFinish ?></strong></div>
                </div>
            </div>
            <?php endif; ?>
            <!-- Item -->
            <?php if(isset($nbProduict) || $nbProduict != NULL): ?>
            <div class="col-xl-4 col-sm-6">
                <div class="item d-flex align-items-center">
                    <div class="icon bg-orange"><i class="icon-check"></i></div>
                    <div class="title"><span>Produits &<br>services</span>
                        <div class="progress">
                            <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-orange"></div>
                        </div>
                    </div>
                    <div class="number"><strong><?= $nbProduict ?></strong></div>
                </div>
            </div>
            <?php endif; ?>
            <!-- Item -->
            <?php if(isset($sumTransactionToday) || $sumTransactionToday != NULL): ?>
            <div class="col-xl-4 col-sm-6">
                <div class="item d-flex align-items-center">
                    <div class="icon bg-green"><i class="icon-bill"></i></div>
                    <div class="title"><span>Montant Transaction<br>de la journée</span>
                        <div class="progress">
                            <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-green"></div>
                        </div>
                    </div>
                    <div class="number"><strong><?= $sumTransactionToday ?></strong></div>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</section>
<?php require __DIR__."/footer.phtml" ?>