<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caisse pas cher - Dashboard</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="<?= DOMAINE ?>css/bootstrap.min.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="<?= DOMAINE ?>css/Poppins.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="<?= DOMAINE ?>css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="<?= DOMAINE ?>css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="<?= DOMAINE ?>img/favicon.ico">
    <!-- Font Awesome CDN-->
    <!-- you can replace it by local Font Awesome-->
    <script src="<?= DOMAINE ?>css/99347ac47f.js"></script>
    <!-- Font Icons CSS-->
    <link rel="stylesheet" href="<?= DOMAINE ?>css/icons.css">

  </head>