<?php require __DIR__."/header.phtml" ?>
<div class="page home-page">
      <!-- Main Navbar-->
      <header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <!-- Navbar Header-->
              <div class="navbar-header">
                <!-- Navbar Brand --><a href="index.html" class="navbar-brand">
                  <div class="brand-text brand-big hidden-lg-down"><span>Caisse </span><strong>pas Cher</strong></div>
                  <div class="brand-text brand-small"><strong>CPC</strong></div></a>
                <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
              </div>
              <!-- Navbar Menu -->
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <!-- Logout    -->
                <li class="nav-item"><a href="/logout" class="nav-link logout">Logout<i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="page-content d-flex align-items-stretch">
        <!-- Side Navbar -->
        <nav class="side-navbar">
          <!-- Sidebar Header-->
          <div class="sidebar-header d-flex align-items-center">
            <div class="title">
              <h1 class="h4"><?= $user["firstname"]." ".$user["lastname"] ?></h1>
              <p><?= $user["compagny_name"] ?></p>
            </div>
          </div>
          <!-- Sidebar Navidation Menus--><span class="heading">Menu</span>
          <ul class="list-unstyled">
            <li class="active"> <a href="/dashboard"><i class="icon-home"></i>Accueil</a></li>
            <li class="active"> <a href="/client"><i class="icon-user"></i>Clients</a></li>
            <li class="active"> <a href="/employee"><i class="icon-list"></i>Employés</a></li>
            <li class="active"> <a href="/product"><i class="icon-bill"></i>Produits & services</a></li>
            <li class="active"> <a href="/categories"><i class="icon-grid"></i>Catégories</a></li>
            <li class="active"> <a href="/payment"><i class="icon-website"></i>Moyens de paiements</a></li>
            <li><a href="#dashvariants" aria-expanded="false" data-toggle="collapse"> <i class="icon-pencil-case"></i>Transactions</a>
              <ul id="dashvariants" class="collapse list-unstyled">
                <li><a href="/transaction">Transactions - Toutes </a></li>
                <li><a href="/transaction-end">Transactions terminées</a></li>
                <li><a href="/transaction-cancel">Transactions annulées</a></li>
              </ul>
            </li>
            <li class="active"> <a href="/account-list"><i class="icon-bars"></i>Comptes</a></li>
            <li class="active"> <a href="/config"><i class="icon-clock"></i>Config</a></li>
        </nav>
        <div class="content-inner">
          <!-- Page Header-->
          <header class="page-header">
            <div class="container-fluid">
              <h2 class="no-margin-bottom">Administration</h2>
            </div>
          </header>