<?php require __DIR__."/menuregister.phtml" ?>
<!-- Dashboard Counts Section -->

           <section class="forms">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- Form Elements -->
                            <div class="col-lg-12">
                                <div class="card">
                
                                   <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Nouveau client</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form-horizontal" method="POST">
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Nom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" id="firstname" name="firstname" value="" parceholder="Entrez le nom du client" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Prénom</label>
                                                <div class="col-sm-7">
                                                    <input type="text" id="lastname" name="lastname" value="" parceholder="Entrez le prenom du client" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Societé</label>
                                                <div class="col-sm-7">
                                                    <input type="text" name="compagny_name" id="compagny_name" value="" parceholder="Entrez le nom de societé" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Email
                                                </label>
                                                <div class="col-sm-7">
                                                    <input type="email" id="email" name="email" value="" parceholder="Entrez l'adresse email du client" class="form-control">
                                                </div>
                                            </div>
                                           
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-2">
                                                    <a href="/register" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Ajouter</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
        
 

<?php require __DIR__."/footer.phtml" ?>

 <script>
  
  
  $(".form-horizontal").validate({

    rules: {

        firstname: {
               required: true,
            },
        lastname: {
               required: true,
            },
            
            
        compagny_name: {
               required: true,
            },
            
        email: {
                required: true,
                email:true, 
            },
            

        
      },
    
    messages: {
        firstname: "Entrer le nom",
        lastname: "Entrer le  pr&eacute;nom",
        compagny_name: "Entrez le nom de societé",
        email: "Entrer une adresse mail valide"
    },
    
    
    submitHandler: function(form, event)
    { 
       event.preventDefault();
        form.submit();

    },
 
    

    errorElement : 'div',
    errorPlacement: function(error, element) {
      var placement = $(element).data('error');
      if (placement) {
        $(placement).append(error)
      } else {
        error.insertAfter(element);
      }
    }
 });
  
  </script>     