<?php require __DIR__."/../menu.phtml" ?>
      
                <section class="tables">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                
                                <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <!-- <a href="/dashboard" class="dropdown-item remove"> <i class="fa fa-times"></i>Close</a> -->
                                                <a href="/account-add" class="dropdown-item"> <i class="fa fa-gear"></i>Ajouter un compte</a>
                                            </div>
                                        </div>
                                    </div>
                                
                                
                                 <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" class="modal fade text-left" style="display: none;" aria-hidden="true">
                                        <div role="document" class="modal-dialog" style=" margin-top: 10%; ">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h4 id="exampleModalLabel" class="modal-title">Suppression</h4>
                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                            <p>Ce compte va être définitivement supprimé?</p>
                                            <input type="hidden" id="usertodel" name="usertodel" value=""/>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Non</button>
                                            <button type="button" class="btn btn-primary" onclick="DeleteUser();">Oui</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                
                                
                                
                                   
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Liste des comptes</h3>
                                    </div>
                                    <div class="card-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <?php   
                                                        foreach($accounts[0] as $key => $val):
                                                            
                                                           
                                                            if($key == "idUsers")continue;
                                                            elseif($key == "actived")  
                                                                 $key = "État";
                                                            elseif($key == "firstname")
                                                                $key = "Nom";
                                                            elseif($key == "lastname")
                                                                $key = "Prénom";
                                                            elseif($key == "compagny_name")
                                                                $key = "Societé";
                                                            elseif($key == "email")
                                                                $key = "Email";
                                                
                                                        ?>
                                                    <th>
                                                        <?= $key ?>
                                                    </th>
                                                    <?php endforeach; ?>
                                                </tr>
                                            </thead>
                                            <?php foreach($accounts as $account): ?>
                                            <tbody>
                                                <tr>
                                                    <?php   
                                                        foreach($account as $key => $val):
                                                            if($key == "idUsers")   continue;
                                                    ?>
                                                                
                                                    <td>
                                                    <?php
                                                        if($key == "actived") 
                                                            {
                                                               if($val == '0')   echo "désactivé";
                                                               if($val == '1')   echo "Activé";
                                                            }
                                                            else echo $val;
                                                        
                                                       ?>
                                                       
                                                       
                                                    </td>
                                                    
                                                   
                                                    <?php endforeach; ?>
                                                    <td>
                                                    <?php
                                                          $use = $account['idUsers'];
                                                          $act = $account['actived'];
                                                                
                                                                 echo '<th><a href="/account/'.$account['idUsers'].'" class="btn btn-primary">Détail</a>&nbsp;';
                                                                if($act == 0)  echo '<a href="/account-activate/'.$account['idUsers'].'" class="btn btn-primary">Activer</a>';
                                                                if($act == 1)  echo '<a href="/account-disactivate/'.$account['idUsers'].'" class="btn btn-primary">Désactiver</a>';
                                                                
                                                                echo "&nbsp;<a  href='#' data-toggle='modal' data-target='#myModal' class='btn btn-warning' onclick=\"$('#usertodel').val('$use');\">Supprimer</a></th>";
                                                     ?>       
                                                    </td>
                                                    
                                                </tr>
                                            </tbody>
                                            <?php endforeach; ?>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                
<script>

function DeleteUser(){
    var Id = $('#usertodel').val();
    location.href = '/account-delete/'+Id;
  
}

</script>

<?php require __DIR__."/../footer.phtml" ?>
            
            
            
            
            