<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item active">Clients</li>
                    </div>
                </ul>
                <section class="tables">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <!-- <a href="/dashboard" class="dropdown-item remove"> <i class="fa fa-times"></i>Close</a> -->
                                                <a href="/client-add" class="dropdown-item"> <i class="fa fa-gear"></i>Ajouter client</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Liste des clients</h3>
                                    </div>
                                    <div class="card-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <?php   
                                                        foreach($clients[0] as $key => $val):
                                                            if($key == "idClients")
                                                                continue;
                                                            elseif($key == "firstname")
                                                                $key = "Nom";
                                                            elseif($key == "lastname")
                                                                $key = "Prénom";
                                                            elseif($key == "phonenumber")
                                                                $key = "Téléphone";
                                                            elseif($key == "email")
                                                                $key = "Email";
                                                            elseif($key == "postcode")
                                                                $key = "Code postal";
                                                            elseif($key == "created")
                                                                $key = "Date de création";
                                                        ?>
                                                    <th>
                                                        <?= $key ?>
                                                    </th>
                                                    <?php endforeach; ?>
                                                </tr>
                                            </thead>
                                            <?php foreach($clients as $client): ?>
                                            <tbody>
                                                <tr>
                                                    <?php   
                                                        foreach($client as $key => $val):
                                                            if($key == "idClients")
                                                                continue; ?>
                                                    <td>
                                                        <?= $val ?>
                                                    </td>
                                                    <?php endforeach; ?>
                                                    <th>
                                                        <a href="/client/<?= $client['idClients'] ?>" class="btn btn-primary">Détail</a>
                                                    </th>
                                                </tr>
                                            </tbody>
                                            <?php endforeach; ?>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            <?php require __DIR__."/../footer.phtml" ?>