<?php require __DIR__."/../menu.phtml" ?>
                <!-- Breadcrumb-->
                <ul class="breadcrumb">
                    <div class="container-fluid">
                        <li class="breadcrumb-item"><a href="/dashboard">Accueil</a></li>
                        <li class="breadcrumb-item active">Moyens de paiements</li>
                    </div>
                </ul>
                <section class="tables">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-close">
                                        <div class="dropdown">
                                            <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                                            <div aria-labelledby="closeCard" class="dropdown-menu has-shadow">
                                                <!-- <a href="/dashboard" class="dropdown-item remove"> <i class="fa fa-times"></i>Close</a> -->
                                                <a href="/payment-add" class="dropdown-item"> <i class="fa fa-gear"></i>Ajouter un moyen de paiement</a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" class="modal fade text-left" style="display: none;" aria-hidden="true">
                                        <div role="document" class="modal-dialog" style=" margin-top: 10%; ">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h4 id="exampleModalLabel" class="modal-title">Suppression</h4>
                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                            <p>Êtes-vous sûr de vouloir supprimer ce moyen de paiement ?</p>
                                            <input type="hidden" id="paytodel" name="paytodel" value=""/>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Non</button>
                                            <button type="button" class="btn btn-primary" onclick="DeletePay();">Oui</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    
                                    
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Liste des moyens de paiement</h3>
                                    </div>
                                    <div class="card-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <?php foreach($payments[0] as $key => $val):
                                                        if(($key == "UserConfigs_has_PaymentMean_Id")|| ($key == "Id_User"))
                                                            continue;
                                                        elseif($key == "PaymentLabel")
                                                            $key = "Moyen de paiement"; ?>
                                                    <th>
                                                        <?= $key ?>
                                                    </th>
                                                    <?php endforeach; ?>
                                                </tr>
                                            </thead>
                                            <?php foreach($payments as $payment): ?>
                                            <tbody>
                                                <tr>
                                                    <?php   
                                                        foreach($payment as $key => $val):
                                                            if(($key == "UserConfigs_has_PaymentMean_Id")|| ($key == "Id_User"))
                                                                continue; ?>
                                                    <td>
                                                          <?php echo utf8_decode($val); ?>
                                                    </td>
                                                    <?php endforeach; ?>
                                                    <th>
                                                        <a href="/payment/<?= $payment['UserConfigs_has_PaymentMean_Id'] ?>" class="btn btn-primary">Détail</a>
                                                        <a  href="#" data-toggle="modal" data-target="#myModal" class="btn btn-warning" onclick="$('#paytodel').val('<?=$payment['UserConfigs_has_PaymentMean_Id']?>');">Supprimer</a>
                                                     
                                                    </th>
                                                </tr>
                                            </tbody>
                                            <?php endforeach; ?>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                
<script>
function DeletePay(){
    var Id = $('#paytodel').val();
    location.href = '/payment-delete/'+Id;
}

</script>
            <?php require __DIR__."/../footer.phtml" ?>