<?php require __DIR__."/../menuregister.phtml" ?>
        
                <section class="tables">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-header d-flex align-items-center">
                                        <h3 class="h4">Profil</h3>
                                    </div>
                                    <div class="card-body">
                                    
                                         <form class="form-horizontal" method="POST">
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Login</label>
                                                <div class="col-sm-6">
                                                    <input type="text" id="login" name="login" value="<?=$user['username']?>" parceholder="Entrez le login" class="form-control" disabled="true"/>
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Mot de passe</label>
                                                <div class="col-sm-6">
                                                    <input type="password" id="pass" name="pass" value="" parceholder="Entrez le mot de passe" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <div class="form-group row">
                                                <label class="col-sm-2 form-control-label">Confirmation</label>
                                                <div class="col-sm-6">
                                                    <input type="password" id="confirm" name="confirm" value="" parceholder="Entrez la confirmation" class="form-control">
                                                </div>
                                            </div>
                                            <div class="line"></div>
                                            <br /><b></b>
                                           
                                            <div class="form-group row">
                                                <div class="col-sm-4 offset-sm-3">
                                                    <a href="/register-list" class="btn btn-secondary">Annuler</a>
                                                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                                                </div>
                                            </div>
                                        </form>
                                     
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
<script>
function DeleteEmployee(){
    var Id = $('#emptodel').val();
    location.href = '/employee-delete/'+Id;
}


</script>
            <?php require __DIR__."/../footer.phtml" ?>
            
            
<script>

  
  $(".form-horizontal").validate({

    rules: {

        login: {
               required: true,
               minlength:5,
            },
            
            
        pass: {
                   equalTo: "#confirm",
                    minlength:5,
            }, 
        
        confirm: {
                   equalTo: "#pass",
                    minlength:5,
            }, 
      },
    
    messages: {
        login: {
                 required  : "Entrer le login",
                 minlength : " Minimum 5 caractères",
            
        },
        pass: {
                  minlength : " Minimum 5 caractères",
                  equalTo :"Le mot de passe et la confirmation doivent être identiques",
                
                
              },
        confirm: {
                   minlength : " Minimum 5 caractères",
                   equalTo : "Le mot de passe et la confirmation doivent être identiques",
                   
        }
        
    },
    
    
    submitHandler: function(form, event)
    { 
       event.preventDefault();
        form.submit();

    },
 
    

    errorElement : 'div',
    errorPlacement: function(error, element) {
      var placement = $(element).data('error');
      if (placement) {
        $(placement).append(error)
      } else {
        error.insertAfter(element);
      }
    }
 });


</script>